name: Unzip Project 2

on:
  workflow_dispatch:  # Run this manually from the Actions tab

permissions:
  contents: write  # Required so Actions can push changes

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensure GITHUB_TOKEN is available for push

      - name: List files for debug
        run: ls -la

      - name: Unzip project
        run: |
          if [ -f "Switch2Launcher_v4_upload.zip" ]; then
            mkdir extracted
            unzip -q Switch2Launcher_v4_upload.zip -d extracted
            rm Switch2Launcher_v4_upload.zip
            rsync -av extracted/ ./
            rm -rf extracted
          else
            echo "ZIP file not found!"
            exit 1
          fi

      - name: Commit unzipped files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped project" || echo "No changes to commit"
          git push
