name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up JDK
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: Switch2Launcher-APK
          path: app/build/outputs/apk/debug/app-debug.apk
