name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cd
        run: cd Switch2Launcher_Full

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew || echo "No gradlew found, skipping chmod"

      - name: Build with Gradle
        run: ./gradlew assembleDebug || gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Switch2Launcher-APK
          path: app/build/outputs/apk/debug/app-debug.apk
