name: Unzip Project

on:
  workflow_dispatch: # Manual trigger

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip project
        run: |
          mkdir extracted
          unzip Switch2Launcher_v4_upload.zip -d extracted
          rm Switch2Launcher_v4_upload.zip
          mv extracted/* .
          rm -rf extracted

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped project"
          git push
